[program:praeviseo-frontend]
process_name=%(program_name)s
directory=/var/www/seo-engine/frontend
command=/usr/bin/node /var/www/seo-engine/frontend/node_modules/next/dist/bin/next start --hostname 127.0.0.1 --port 3000
autostart=true
autorestart=true
startsecs=5
stopwaitsecs=30
user=root
redirect_stderr=true
stdout_logfile=/var/log/supervisor/praeviseo-frontend.log
