<?php

return [
    'site' => [
        'id' => env('SEO_SITE_ID', 'default'),
        'name' => env('SEO_SITE_NAME', config('app.name')),
        'url' => env('SEO_SITE_URL', config('app.url')),
        'locale' => env('SEO_LOCALE', str_replace('_', '-', (string) env('APP_LOCALE', config('app.locale', 'en')))),
        'niche' => env('SEO_NICHE', 'generic'),
        'slug_prefix' => env('SEO_SLUG_PREFIX', ''),
    ],
    'quality' => [
        'min_word_count' => env('SEO_MIN_WORD_COUNT', 1300),
        'min_faq_count' => env('SEO_MIN_FAQ_COUNT', 5),
        'min_h2_count' => env('SEO_MIN_H2_COUNT', 6),
        'min_h3_count' => env('SEO_MIN_H3_COUNT', 5),
        'min_topical_score' => env('SEO_MIN_TOPICAL_SCORE', 82),
        'min_quality_score' => env('SEO_MIN_QUALITY_SCORE', 82),
        'min_profession_specific_signals' => env('SEO_MIN_PROFESSION_SIGNALS', 6),
        'blocked_signals' => ['crypto', 'casino', 'trading', 'viral', 'dropshipping', 'marketing automation'],
        'image_alt_required_terms' => array_values(array_filter(array_map('trim', explode(',', (string) env('SEO_IMAGE_ALT_REQUIRED_TERMS', ''))))),
        'image_prompt_required_terms' => array_values(array_filter(array_map('trim', explode(',', (string) env('SEO_IMAGE_PROMPT_REQUIRED_TERMS', ''))))),
    ],
    'search_console' => [
        'enabled' => env('SEARCH_CONSOLE_ENABLED', false),
        'site_url' => env('GOOGLE_SEARCH_CONSOLE_SITE_URL', env('APP_URL')),
        'credentials' => env('GOOGLE_APPLICATION_CREDENTIALS'),
        'access_token' => env('GOOGLE_SEARCH_CONSOLE_ACCESS_TOKEN'),
        'language_code' => env('GOOGLE_SEARCH_CONSOLE_LANGUAGE_CODE', env('SEO_LOCALE', str_replace('_', '-', (string) env('APP_LOCALE', config('app.locale', 'en'))))),
    ],
    'embeddings' => [
        'enabled' => env('SEO_EMBEDDINGS_ENABLED', false),
        'model' => env('SEO_EMBEDDINGS_MODEL', 'text-embedding-3-small'),
        'dimensions' => env('SEO_EMBEDDINGS_DIMENSIONS', 1536),
        'page_version' => env('SEO_EMBEDDINGS_PAGE_VERSION', 'page_v1'),
        'query_version' => env('SEO_EMBEDDINGS_QUERY_VERSION', 'query_v1'),
        'internal_link_threshold' => (float) env('SEO_INTERNAL_LINK_SIMILARITY', 0.84),
        'max_internal_link_suggestions' => (int) env('SEO_MAX_INTERNAL_LINK_SUGGESTIONS', 4),
        'cannibalization_threshold' => (float) env('SEO_CANNIBALIZATION_SIMILARITY', 0.9),
        'max_cannibalization_risks' => (int) env('SEO_MAX_CANNIBALIZATION_RISKS', 4),
        'cannibalization_impression_threshold' => (int) env('SEO_CANNIBALIZATION_IMPRESSION_THRESHOLD', 50),
        'cannibalization_position_gap_threshold' => (float) env('SEO_CANNIBALIZATION_POSITION_GAP_THRESHOLD', 5),
        'query_match_threshold' => (float) env('SEO_QUERY_MATCH_THRESHOLD', 0.78),
        'query_match_wrong_page_gap' => (float) env('SEO_QUERY_MATCH_WRONG_PAGE_GAP', 0.06),
        'query_match_wrong_page_min_score' => (float) env('SEO_QUERY_MATCH_WRONG_PAGE_MIN_SCORE', 0.84),
        'query_match_refresh_position_threshold' => (float) env('SEO_QUERY_MATCH_REFRESH_POSITION', 12),
        'query_match_impression_threshold' => (int) env('SEO_QUERY_MATCH_IMPRESSIONS', 30),
        'query_match_min_score' => (float) env('SEO_QUERY_MATCH_MIN_SCORE', 0.6),
        'query_match_min_impressions' => (int) env('SEO_QUERY_MATCH_MIN_IMPRESSIONS', 5),
        'query_match_create_min_score' => (float) env('SEO_QUERY_MATCH_CREATE_MIN_SCORE', 0.78),
        'query_match_create_min_impressions' => (int) env('SEO_QUERY_MATCH_CREATE_MIN_IMPRESSIONS', 20),
        'query_match_create_max_position' => (float) env('SEO_QUERY_MATCH_CREATE_MAX_POSITION', 25),
        'max_query_opportunities' => (int) env('SEO_MAX_QUERY_OPPORTUNITIES', 6),
        'policy' => [
            'same_cluster_bonus' => (float) env('SEO_SEMANTIC_SAME_CLUSTER_BONUS', 0.04),
            'cross_cluster_penalty' => (float) env('SEO_SEMANTIC_CROSS_CLUSTER_PENALTY', 0.03),
            'same_intent_bonus' => (float) env('SEO_SEMANTIC_SAME_INTENT_BONUS', 0.05),
            'generic_target_penalty' => (float) env('SEO_SEMANTIC_GENERIC_TARGET_PENALTY', 0.02),
            'pillar_target_bonus' => (float) env('SEO_SEMANTIC_PILLAR_TARGET_BONUS', 0.02),
            'strong_target_penalty' => (float) env('SEO_SEMANTIC_STRONG_TARGET_PENALTY', 0.02),
            'strong_target_inbound_threshold' => (int) env('SEO_SEMANTIC_STRONG_TARGET_INBOUND_THRESHOLD', 6),
            'max_cross_cluster_suggestions' => (int) env('SEO_SEMANTIC_MAX_CROSS_CLUSTER_SUGGESTIONS', 1),
            'max_generic_targets' => (int) env('SEO_SEMANTIC_MAX_GENERIC_TARGETS', 2),
            'generic_terms' => array_values(array_filter(array_map('trim', explode(',', (string) env('SEO_SEMANTIC_GENERIC_TERMS', ''))))),
            'pillar_terms' => array_values(array_filter(array_map('trim', explode(',', (string) env('SEO_SEMANTIC_PILLAR_TERMS', ''))))),
            'intent_families' => [],
        ],
    ],
    'contracts' => [
        'cannibalization_action_decider' => \Ofyre\SeoEngine\Services\Embeddings\DefaultCannibalizationActionDecider::class,
        'content_signal_provider' => null,
        'page_status_labeler' => null,
        'embedding_provider' => \Ofyre\SeoEngine\Services\Embeddings\OpenAiEmbeddingProvider::class,
        'signal_suggestion_formatter' => null,
        'embeddable_content_repository' => null,
        'historical_importer' => null,
        'image_prompt_provider' => null,
        'internal_link_provider' => null,
        'niche_blueprint_provider' => null,
        'niche_content_provider' => null,
        'prioritized_page_provider' => null,
        'prompt_profile_provider' => null,
        'rewrite_access_decider' => null,
        'search_console_token_provider' => null,
        'semantic_link_policy_provider' => \Ofyre\SeoEngine\Services\Embeddings\ConfigDrivenSemanticLinkPolicy::class,
        'semantic_link_repository' => null,
        'seo_audit_persister' => null,
        'seo_cockpit_repository' => null,
        'seo_feedback_loop_driver' => null,
        'seo_generation_driver' => null,
        'seo_page_repository' => null,
        'seo_suggestion_persister' => null,
        'vector_store' => null,
    ],
    'monitoring' => [
        'auto_improve_threshold' => (int) env('SEO_AUTO_IMPROVE_THRESHOLD', 85),
        'published_degradation_threshold' => (int) env('SEO_PUBLISHED_DEGRADATION_THRESHOLD', 60),
    ],

    'scheduler' => [
        'enabled' => env('SEO_SCHEDULER_ENABLED', true),
        'commands' => [
            [
                'command' => 'seo:import-history --windows=7,28,90,180,365',
                'frequency' => 'dailyAt',
                'argument' => '02:50',
                'withoutOverlapping' => true,
            ],
            [
                'command' => 'seo:monitor --queue',
                'frequency' => 'dailyAt',
                'argument' => '03:20',
                'withoutOverlapping' => true,
            ],
            [
                'command' => 'seo:check-indexation',
                'frequency' => 'dailyAt',
                'argument' => '03:50',
                'withoutOverlapping' => true,
            ],
            [
                'command' => 'seo:feedback-loop',
                'frequency' => 'dailyAt',
                'argument' => '04:20',
                'withoutOverlapping' => true,
            ],
            [
                'command' => 'seo:semantic-links',
                'frequency' => 'dailyAt',
                'argument' => '04:35',
                'withoutOverlapping' => true,
            ],
            [
                'command' => 'seo:detect-cannibalization',
                'frequency' => 'dailyAt',
                'argument' => '04:45',
                'withoutOverlapping' => true,
            ],
            [
                'command' => 'seo:match-query-pages',
                'frequency' => 'dailyAt',
                'argument' => '04:55',
                'withoutOverlapping' => true,
            ],
            [
                'command' => 'seo:queue-signal-suggestions',
                'frequency' => 'dailyAt',
                'argument' => '05:05',
                'withoutOverlapping' => true,
            ],
            [
                'command' => 'seo:analyze-brand-images',
                'frequency' => 'weeklyOn',
                'argument' => [1, '02:40'],
                'withoutOverlapping' => true,
            ],
            [
                'command' => 'seo:refresh-content --days=45',
                'frequency' => 'weeklyOn',
                'argument' => [2, '04:10'],
                'withoutOverlapping' => true,
            ],
        ],
    ],
];
