<?php

return [
    'site' => [
        'id'          => env('SEO_SITE_ID', 'default'),
        'name'        => env('SEO_SITE_NAME', 'My Site'),
        'url'         => env('SEO_SITE_URL', env('APP_URL', '')),
        'locale'      => env('SEO_LOCALE', env('APP_LOCALE', 'en')),
        'niche'       => env('SEO_NICHE', 'general'),
        'slug_prefix' => env('SEO_SLUG_PREFIX', ''),
    ],
    'quality' => [
        'min_word_count' => env('SEO_MIN_WORD_COUNT', 1300),
        'min_faq_count' => env('SEO_MIN_FAQ_COUNT', 5),
        'min_h2_count' => env('SEO_MIN_H2_COUNT', 6),
        'min_h3_count' => env('SEO_MIN_H3_COUNT', 5),
        'min_topical_score' => env('SEO_MIN_TOPICAL_SCORE', 82),
        'min_quality_score' => env('SEO_MIN_QUALITY_SCORE', 82),
        'min_profession_specific_signals' => env('SEO_MIN_PROFESSION_SIGNALS', 4),
        'blocked_signals' => ['crypto', 'casino', 'trading', 'viral', 'dropshipping', 'marketing automation'],
        'image_alt_required_terms' => [],
        'image_prompt_required_terms' => [],
    ],
    'search_console' => [
        'enabled' => env('SEARCH_CONSOLE_ENABLED', true),
        'site_url' => env('GOOGLE_SEARCH_CONSOLE_SITE_URL', ''),
        'credentials' => env('GOOGLE_APPLICATION_CREDENTIALS', storage_path('google/service-account.json')),
        'access_token' => env('GOOGLE_SEARCH_CONSOLE_ACCESS_TOKEN'),
        'language_code' => env('GOOGLE_SEARCH_CONSOLE_LANGUAGE_CODE', env('SEO_LOCALE', 'fr-FR')),
    ],
    'embeddings' => [
        'enabled' => env('SEO_EMBEDDINGS_ENABLED', true),
        'model' => env('SEO_EMBEDDINGS_MODEL', 'text-embedding-3-small'),
        'dimensions' => env('SEO_EMBEDDINGS_DIMENSIONS', 1536),
        'page_version' => env('SEO_EMBEDDINGS_PAGE_VERSION', 'page_v1'),
        'query_version' => env('SEO_EMBEDDINGS_QUERY_VERSION', 'query_v1'),
        'internal_link_threshold' => (float) env('SEO_INTERNAL_LINK_SIMILARITY', 0.84),
        'max_internal_link_suggestions' => (int) env('SEO_MAX_INTERNAL_LINK_SUGGESTIONS', 4),
        'cannibalization_threshold' => (float) env('SEO_CANNIBALIZATION_SIMILARITY', 0.9),
        'max_cannibalization_risks' => (int) env('SEO_MAX_CANNIBALIZATION_RISKS', 4),
        'cannibalization_impression_threshold' => (int) env('SEO_CANNIBALIZATION_IMPRESSION_THRESHOLD', 50),
        'cannibalization_position_gap_threshold' => (float) env('SEO_CANNIBALIZATION_POSITION_GAP_THRESHOLD', 5),
        'query_match_threshold' => (float) env('SEO_QUERY_MATCH_THRESHOLD', 0.78),
        'query_match_wrong_page_gap' => (float) env('SEO_QUERY_MATCH_WRONG_PAGE_GAP', 0.06),
        'query_match_wrong_page_min_score' => (float) env('SEO_QUERY_MATCH_WRONG_PAGE_MIN_SCORE', 0.84),
        'query_match_refresh_position_threshold' => (float) env('SEO_QUERY_MATCH_REFRESH_POSITION', 12),
        'query_match_impression_threshold' => (int) env('SEO_QUERY_MATCH_IMPRESSIONS', 30),
        'query_match_min_score' => (float) env('SEO_QUERY_MATCH_MIN_SCORE', 0.6),
        'query_match_min_impressions' => (int) env('SEO_QUERY_MATCH_MIN_IMPRESSIONS', 5),
        'query_match_create_min_score' => (float) env('SEO_QUERY_MATCH_CREATE_MIN_SCORE', 0.78),
        'query_match_create_min_impressions' => (int) env('SEO_QUERY_MATCH_CREATE_MIN_IMPRESSIONS', 20),
        'query_match_create_max_position' => (float) env('SEO_QUERY_MATCH_CREATE_MAX_POSITION', 25),
        'max_query_opportunities' => (int) env('SEO_MAX_QUERY_OPPORTUNITIES', 6),
        'policy' => [
            'same_cluster_bonus' => (float) env('SEO_SEMANTIC_SAME_CLUSTER_BONUS', 0.04),
            'cross_cluster_penalty' => (float) env('SEO_SEMANTIC_CROSS_CLUSTER_PENALTY', 0.03),
            'same_intent_bonus' => (float) env('SEO_SEMANTIC_SAME_INTENT_BONUS', 0.05),
            'generic_target_penalty' => (float) env('SEO_SEMANTIC_GENERIC_TARGET_PENALTY', 0.02),
            'pillar_target_bonus' => (float) env('SEO_SEMANTIC_PILLAR_TARGET_BONUS', 0.02),
            'strong_target_penalty' => (float) env('SEO_SEMANTIC_STRONG_TARGET_PENALTY', 0.02),
            'strong_target_inbound_threshold' => (int) env('SEO_SEMANTIC_STRONG_TARGET_INBOUND_THRESHOLD', 6),
            'max_cross_cluster_suggestions' => (int) env('SEO_SEMANTIC_MAX_CROSS_CLUSTER_SUGGESTIONS', 1),
            'max_generic_targets' => (int) env('SEO_SEMANTIC_MAX_GENERIC_TARGETS', 2),
            'generic_terms' => (array) env('SEO_SEMANTIC_GENERIC_TERMS', ''),
            'pillar_terms' => (array) env('SEO_SEMANTIC_PILLAR_TERMS', ''),
            'intent_families' => [],
        ],
    ],
    'contracts' => [
        'cannibalization_action_decider' => \Ofyre\SeoEngine\Services\Embeddings\DefaultCannibalizationActionDecider::class,
        'content_signal_provider' => \App\Services\GenericContentSignalProvider::class,
        'page_status_labeler' => \App\Services\RuntimePageStatusLabeler::class,
        'embedding_provider' => \App\SeoBridge\Embeddings\OpenAiEmbeddingProvider::class,
        'signal_suggestion_formatter' => \App\Services\RuntimeSignalSuggestionFormatter::class,
        'embeddable_content_repository' => \App\SeoBridge\Repositories\EmbeddableContentRepository::class,
        'historical_importer' => \App\SeoBridge\SearchConsole\SearchConsoleHistoricalImporter::class,
        'image_prompt_provider' => \App\SeoPresets\Generic\GenericImagePromptProvider::class,
        'internal_link_provider' => \App\SeoPresets\Generic\GenericInternalLinkProvider::class,
        'niche_blueprint_provider' => \App\SeoPresets\Generic\GenericBlueprintProvider::class,
        'niche_content_provider' => \App\SeoPresets\Generic\GenericContentProfile::class,
        'prioritized_page_provider' => \App\Services\DatabasePrioritizedPageProvider::class,
        'prompt_profile_provider' => \App\SeoPresets\Generic\GenericPromptProfile::class,
        'rewrite_access_decider' => \App\Services\SeoOverrideService::class,
        'search_console_token_provider' => \Ofyre\SeoEngine\Services\SearchConsole\GoogleServiceAccountTokenService::class,
        'semantic_link_policy_provider' => \Ofyre\SeoEngine\Services\Embeddings\ConfigDrivenSemanticLinkPolicy::class,
        'semantic_link_repository' => \App\SeoBridge\Repositories\MysqlSemanticLinkRepository::class,
        'seo_audit_persister' => \App\SeoBridge\Persisters\DatabaseSeoAuditPersister::class,
        'seo_cockpit_repository' => \App\SeoBridge\Repositories\DatabaseSeoCockpitRepository::class,
        'seo_feedback_loop_driver' => \App\SeoBridge\Feedback\DatabaseSeoFeedbackLoopDriver::class,
        'seo_generation_driver' => \App\SeoBridge\Drivers\OpenAiSeoGenerationDriver::class,
        'seo_page_repository' => \App\SeoBridge\Repositories\MysqlSeoPageRepository::class,
        'seo_suggestion_persister' => \App\SeoBridge\Persisters\DatabaseSeoSuggestionPersister::class,
        'vector_store' => \App\SeoBridge\VectorStore\MysqlVectorStore::class,
    ],
    'monitoring' => [
        'auto_improve_threshold' => (int) env('SEO_AUTO_IMPROVE_THRESHOLD', 85),
        'published_degradation_threshold' => (int) env('SEO_PUBLISHED_DEGRADATION_THRESHOLD', 60),
    ],
    'scheduler' => [
        'enabled' => env('SEO_SCHEDULER_ENABLED', true),
        'commands' => [
            ['command' => 'seo:import-history --windows=7,28,90,180,365', 'frequency' => 'dailyAt', 'argument' => '02:40', 'withoutOverlapping' => true],
            ['command' => 'seo:recalculate-scores --audits', 'frequency' => 'dailyAt', 'argument' => '03:10', 'withoutOverlapping' => true],
            ['command' => 'seo:feedback-loop', 'frequency' => 'dailyAt', 'argument' => '03:35', 'withoutOverlapping' => true],
            ['command' => 'seo:embed-content --force', 'frequency' => 'dailyAt', 'argument' => '04:00', 'withoutOverlapping' => true],
            ['command' => 'seo:semantic-links', 'frequency' => 'dailyAt', 'argument' => '04:20', 'withoutOverlapping' => true],
            ['command' => 'seo:detect-cannibalization', 'frequency' => 'dailyAt', 'argument' => '04:30', 'withoutOverlapping' => true],
            ['command' => 'seo:match-query-pages --force', 'frequency' => 'dailyAt', 'argument' => '04:40', 'withoutOverlapping' => true],
            ['command' => 'seo:queue-signal-suggestions', 'frequency' => 'dailyAt', 'argument' => '04:50', 'withoutOverlapping' => true],
        ],
    ],
];
